blog_project/blog_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

post_list = views.BlogPostViewSet.as_view({
    'get': 'list',
    'post': 'create',
})

post_detail = views.BlogPostViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'delete': 'destroy',
})

like_list = views.LikeViewSet.as_view({
    'post': 'create'
})

router = DefaultRouter()
router.register(r"post", views.BlogPostViewSet)
router.register(r"user", views.UserViewSet)
router.register(r"comment", views.CommentViewSet)
router.register(r"like", views.LikeViewSet)

app_name = 'blog_app'
urlpatterns = [
    path("api/", include(router.urls)),
    
    path("api/post", post_list, name="post_list"),
    path("api/post/<int:pk>", post_detail, name="post_detail"),
    path("api/like", like_list, name="like_list"),
    path('post/<int:post_id>/', views.board, name='post_title'),
    
    path("", views.board_client, name="board_client"),
    path("login/", views.custom_login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("write/", views.write, name="write"),
    path("write/<int:blog_post_id>", views.write, name="write_with_id"),
    path("board/<int:blog_post_id>", views.board, name="board"),

    # ai
    path('autocomplete/', views.autocomplete, name='autocomplete'),

    # haystack
    path('search', views.search_view, name='search_view'),
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog_app.urls")),
    path('summernote/', include('django_summernote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.postgres.fields import ArrayField  
from django_summernote import fields as summer_fields

class User(models.Model):
    user_pwd = models.CharField(max_length=20)
    user_email = models.CharField(max_length=100)
    user_name = models.CharField(max_length=20)
    user_login_date = models.DateTimeField(auto_now_add=True)

class Category(models.Model):
    DAILY = 0
    COOKING = 1
    TRAVEL = 2
    MOVIE = 3
    IT = 4
    CATEGORY_CHOICES= [ (DAILY, "일상"), (COOKING, "요리"), (TRAVEL, "여행"), (MOVIE, "영화"), (IT, "IT")]
    category_name = models.IntegerField(choices=CATEGORY_CHOICES, default=DAILY)
    def __str__(self):
        return f"{self.category_name}"
    

class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    summer_fields = summer_fields.SummernoteTextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    upload_date = models.DateTimeField(auto_now_add=True)
    tags = ArrayField(models.CharField(max_length=300), blank=True, null=True)
    like_count = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    img = models.TextField(blank=True, null=True)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    comment = models.TextField()
    chrmt_upload_date = models.DateTimeField(auto_now_add=True)
    like_cnt = models.IntegerField(default=0, null=True)
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    like_upload_date = models.DateTimeField(auto_now_add=True)
    
    

blog_project/blog_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from .models import *
from .serializers import *
from .models import *
import re
import json

# blog post form
from .form import BlogPostForm

# user login, logout, register form
from django.contrib.auth import authenticate, login
from .form import CustomLoginForm

# AI
from django.http import JsonResponse
import openai

# haystack
from haystack.query import SearchQuerySet
from django.http import JsonResponse


class BlogPostViewSet(viewsets.ModelViewSet):
    queryset = BlogPost.objects.all().order_by("-views")
    serializer_class = BlogPostSerializer
    http_method_names = ["get", "post", "put", "delete"]

    def list(self, request):
        queryset = BlogPost.objects.all().filter(status="True").order_by("-views")
        serializer = BlogPostSerializer(queryset, many=True)
        return Response(serializer.data, status=200)

    def create(self, request):
        content = request.data["content"]
        pattern = re.compile("[\"'](\/[^\"']*?)[\"']")
        img = pattern.findall(content)[0]

        data = {
            "user": request.data["user"],
            "title": request.data["title"],
            "content": content,
            "summer_fields": content,
            "category": request.data["category"],
            "img": img,
            "tags": [],  # TODO: 수정
            "status": request.data["status"],
        }

        serializer = BlogPostSerializer(data=data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)

        return Response(serializer.errors, status=400)

    @action(methods=["get"], detail=False)
    def filter(self, request, *args, **kwargs):
        category_id = request.query_params["category"]
        queryset = BlogPost.objects.filter(category=category_id)
        serializer = BlogPostSerializer(queryset, many=True)
        return Response(serializer.data)

    @action(methods=["get"], detail=False)
    def temp_post(self, request):
        queryset = BlogPost.objects.filter(status="False").first()
        serializer = BlogPostSerializer(queryset)
        return Response(serializer.data)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class LikeViewSet(viewsets.ModelViewSet):
    queryset = Like.objects.all()
    serializer_class = LikeSerializer

    # 좋아요 작성/삭제
    def create(self, request):
        like_queryset = Like.objects.filter(
            user=request.data["user"],
            blog_post=request.data["blog_post"],
            comment=request.data["comment"],
        )

        if like_queryset.exists():
            like_queryset.delete()
            comment_queryset = Comment.objects.get(id=request.data["comment"])
            comment_queryset.like_cnt -= 1
            comment_queryset.save()
            data = {"like_cnt": comment_queryset.like_cnt}
            return Response(data=json.dumps(data), status=204)
        else:
            serializer = LikeSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                comment_queryset = Comment.objects.get(id=request.data["comment"])
                comment_queryset.like_cnt += 1
                comment_queryset.save()
                data = {"like_cnt": comment_queryset.like_cnt}
                return Response(data=json.dumps(data), status=201)
            return Response(serializer.errors, status=400)


def custom_login(request):
    # 이미 로그인 되어 있다면
    if request.user.is_authenticated:
        return redirect("board_client")

    form = CustomLoginForm(data=request.POST or None)

    # 아이디 비밀번호를 입력했고
    if request.method == "POST":
        # 해당하는 유저가 있다면
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("blog_app:board_client")

    return render(request, "login.html", {"form": form})


# 메인 화면
def board_client(request):
    return render(request, "board_client.html")


@login_required(login_url="blog_app:login")
def write(request, blog_post_id=None):
    if request.user.is_authenticated:
        form = BlogPostForm()
        return render(request, "board_write.html", {"form": form})


@login_required(login_url="blog_app:login")
def board(request, blog_post_id):
    if request.user.is_authenticated:
        blog_post = BlogPost.objects.get(pk=blog_post_id)
        blog_post.views += 1
        blog_post.save()

        related_posts = BlogPost.objects.filter(
            category=blog_post.category, status="True"
        ).order_by("-id")
        comments = Comment.objects.filter(blog_post=blog_post_id)
        previous_post = (
            BlogPost.objects.filter(id__lt=blog_post_id, status="True").order_by("-id").first()
        )
        next_post = (
            BlogPost.objects.filter(id__gt=blog_post_id, status="True").order_by("id").first()
        )

        context = {
            "blog_post": blog_post,
            "related_posts": related_posts,
            "comments": comments,
            "previous_post": previous_post,
            "next_post": next_post,
        }

        return render(request, "board.html", context)


# haystack
def search_view(request):
    query = request.GET.get("q")
    results = []

    if query:
        results = SearchQuerySet().filter(text=query)

    context = []
    for result in results:
        context.append(
            {
                "id": result.object.id,
                "title": result.title,
                "content": result.content,
                "img": result.object.img,
                "upload_date": result.object.upload_date,
            }
        )

    return JsonResponse(context, safe=False)


# Chat gpt API 사용
openai.api_key = "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"


# 글 자동완성 기능
def autocomplete(request):
    if request.method == "POST":
        # 제목 필드값 가져옴
        prompt = request.POST.get("title")
        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": prompt},
                ],
            )
            # 반환된 응답에서 텍스트 추출해 변수에 저장
            message = response["choices"][0]["message"]["content"]
            print(message)
        except Exception as e:
            message = str(e)
        return JsonResponse({"message": message})
    return render(request, "autocomplete.html")


def logout(request):
    auth_logout(request)
    return redirect("blog_app:board_client")

blog_project/blog_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>📚포스팅검색📚</h1>
        <nav>
            <a href="{% url 'search_view' %}"> 다시 검색하기</a>
        </nav>
    </header>

    <main>
        <main>{% block content %}{% endblock %}</main>
    </main>

    <footer>
        <p>&copy; 2023 yujinkim</p>
    </footer>
</body>
</html>

blog_project/blog_app/templates/board.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/reset.css'%}?{%now "U" %}"/>
        <link rel="stylesheet" href="{% static 'css/header_white.css'%}?{%now "U" %}"/>
        <link rel="stylesheet" href="{% static 'css/footer.css'%}?{%now "U" %}"/>
        <link rel="stylesheet" href="{% static 'css/board.css'%}?{%now "U" %}"/>
        <link rel="icon" href="{% static 'img/common/onenable.png'%}">
        <title>board</title>
    </head>

    <body>
        <header>
            {% include 'header.html' %}
        </header>
        
        <section>
            <div class="main_and_sall_box">
                <div class="main_box">
                    <div class="posting_date"> {{ blog_post.upload_date }} </div>
                    <div class="posting_title"> {{ blog_post.title }} </div>
                    <div class="writer"> {{ blog_post.user }} </div>
                    <div class="content_tag"> 
                        {% if blog_post.category_id == 1 %} 일상
                        {% elif blog_post.category_id == 2 %} 요리
                        {% elif blog_post.category_id == 3 %} 여행
                        {% elif blog_post.category_id == 4 %} 영화
                        {% elif blog_post.category_id == 5 %} IT
                        {% endif %}
                    </div>
                    <div class="posting_content"> {{ blog_post.content|safe }} </div>
                </div>
                <div class ="smallbox">
                    <div class="recommend">
                        <div class="toppic"> Other posts <br> you may like </div>
                        {% for related_post in related_posts %}
                        <div class="sub_posting" onclick=moveToRelatedPost({{ related_post.id }})>
                            <img class="sub_img" src="{{ related_post.img }}">
                            <div class="sub_title"> {{ related_post.title }} </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="button_box">
                <div class="button_flex">
                    <div class ="button_flex gap">
                        <button class="left" id="edit_btn">수정하기</button>
                        <button class="left" id="delete_btn">삭제하기</button>
                    </div>
                    <button id="share_btn">공유하기</button>
                </div>
                <div class="button_flex">
                    <div class="button_flex gap text">
                        {% if next_post %}
                        <span style="opacity: 0.5;">다음글</span>
                        <div class="post-name">
                            <a href="{% url 'blog_app:board' next_post.id %}">
                                {{next_post.title}}</a>
                            {% else %}
                                <span style="opacity: 0.5;">다음글</span>
                                <span class="text">다음 글이 없습니다.</span>
                            {% endif %}
                        </div>
                    </div>
                    <span style="opacity: 0.5;">
                        {{ next_post.upload_date}}</span>
                </div>
                <div class = "button_flex">
                    <div class="button_flex gap text">
                        {% if previous_post %}
                        <span style="opacity: 0.5;">이전글</span>
                        <div class="post-name">
                            <a href="{% url 'blog_app:board' previous_post.id %}">
                                {{previous_post.title}}</a>
                            {% else %}
                                <span style="opacity: 0.5;">이전글</span>
                                <span class="text">이전 글이 없습니다.</span>
                            {% endif %}
                        </div>
                    </div>
                    <span style="opacity: 0.5;">
                        {{ previous_post.upload_date}}</span>
                </div>
            </div>
            
            <div class="comment-box">
                <div name="comment_form" method="POST">
                    <input id="comment_input" placeholder="댓글을 입력해주세요."></input> 
                    <button class="comment-post" onclick=postComment()>댓글 작성</button>
                </div>
                <div class="comment_list">
                    {% if comments %}
                    {% for comment in comments %}
                    <div class="comment" data-comment-id="{{ comment.id }}">
                        <div class="comment_user_img">
                            <div style='width:50px; height: 50px; border-radius: 70%; overflow:hidden;'>
                                <img src="{% static 'img/board/profile.png' %}" style='width:50px; height:50px; object-fit:cover; cursor:pointer;'></img>
                            </div>
                            <div style="display:flex; flex-direction: column; justify-content:space-between;">
                                <div class="comment_user"> {{ comment.user.user_name }}</div>
                                <span>{{ comment.comment }}</span>
                            </div>
                        </div>
                        <div class="action-box"> 
                            <div class="comment_date">{{ comment.chrmt_upload_date }}</div>
                            <div style="display:flex; justify-content: end; gap:10px;">
                                <div>
                                    {% if comment.like_cnt == 0 %}
                                    <img src="{% static 'img/board/like_btn.svg' %}" onclick=likePost(event,'{{comment.id}}')>
                                    {% else %}
                                    <img src="{% static 'img/board/like_active_btn.svg' %}" onclick=likePost(event,'{{comment.id}}')>
                                    {% endif %}
                                    <span class="like_cnt"> {{comment.like_cnt}} </span>
                                </div>
                                <div class="comment_btn">
                                    <button class="comment_delete" onclick="if (window.confirm('삭제하시겠습니까?')) { deleteComment('{{comment.id}}'); }">삭제</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </section>
        <footer> {% include 'footer.html' %} </footer>
</body>
<script src="{% static 'js/board.js' %}"></script>
<script src="{% static 'js/header.js' %}"></script>
{% comment %} <script src="{% static 'js/click.js' %}"></script> {% endcomment %}
</html>

blog_project/blog_app/templates/board_admin.html
{% extends 'base_content.html' %} {% load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/board_admin.css' %}?{% now "U" %}"/>
    <link rel="icon" href="{% static 'img/common/onenable.png'%}">
    <title>메인페이지</title>
  </head>

  <body>
    {% block content %}
    <header>
      <nav>
        <div class="nav_logo"> <img src="{% static "img/common/mylog_white.svg" %}"> </div>
        <div class="nav_side">
          <span title="일상">일상</span>
          <span title="요리">요리</span>
          <span title="여행">여행</span>
          <span title="영화">영화</span>
          <span title="IT">IT</span>
          <span><button class="logout">Logout</button></span>
          <a id="just_write" href="{% url 'write' %}">Just Write!</a>
        </div>
      </nav>
      <section>
        <div class="pop_title_and_content">
          <div class="pop_title">Lorem ipsum dolor</div>
          <div class="pop_content">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
            architecto? Assumenda, distinctio consequuntur omnis nobis nostrum
            doloribus consequatur ipsam necessitatibus iure praesentium cumque
            voluptates, ullam similique beatae. Et, inventore fugit.
          </div>
          <div class="read_more">READ MORE</div>
        </div>
        <img class="pop_img" src="{% static "img/board_client/pop_img.svg" %}">
      </section>
    </header>
    {% endblock %}
  </body>
  <script src="{% static 'js/main.js' %}"></script>  
</html>

blog_project/blog_app/templates/board_client.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/board_client.css'%}?{%now "U" %}"/>
    <link rel="stylesheet" href="{% static 'css/footer.css'%}?{%now "U" %}"/>
    <link rel="stylesheet" href="{% static 'css/header_black.css'%}?{%now "U" %}"/>
    <link rel="icon" href="{% static 'img/common/onenable.png'%}">
    <title>메인페이지</title>
</head>

<body>
    <header>

        {% include 'header.html' %}

        <section>
            <div class='pop_title_and_content'>
                <div class="pop_title"></div>
                <div class="pop_content"> 
                </div>
                <button class="read_more">READ MORE</button>
            </div>
            <img class="pop_img">
        </section>
    </header>
  
    <article>
        <div class="posting_list">
        </div>
    </article>

    <div class="audio-player">
    <audio controls loop autoplay>
        <source src="{% static 'sounds/onepiece1.mp3' %}" type="audio/mp3">
        Your browser does not support the audio element.
    </audio></div>

    <footer> {% include 'footer.html' %} </footer>
    <script src="{% static 'js/main.js' %}"></script>  
    <script src="{% static 'js/header.js' %}"></script>
    <script src="{% static 'js/click.js' %}"></script>
  </body>
</html>

blog_project/blog_app/templates/board_clinet.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>메인페이지</title>
</head>

<body>
    <nav>
        <div class="nav_logo">
            <span>myLOG</span>
        </div>
        <div class="nav_side">
            <span title="일상">일상</span>
            <span title="요리">요리</span>
            <span title="여행">여행</span>
            <span title="영화">영화</span>
            <span title="IT">IT</span>
            <button>Login</button>
        </div>
    </nav>
    </nav>
    <section>
        <header>
            블로그 대문내용
        </header>
        <article>
            블로그 작성내용 불러오는곳
        </article>
    </section>
    <footer>
        피그마 마지막 회색줄
    </footer>
</body>

</html>

blog_project/blog_app/templates/board_write.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/reset.css'%}?{%now "U" %}"/>
    <link rel="stylesheet" href="{% static 'css/header_white.css'%}?{% now "U"%}"/>
    <link rel="stylesheet" href="{% static 'css/board_write.css'%}?{% now "U"%}"/>
    <link rel="stylesheet" href="{% static 'css/footer.css'%}?{% now "U"%}"/>
    <link rel="icon" href="{% static 'img/common/onenable.png'%}">
    

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    <title>write</title>
  </head>
 
  <body>
    <header>
      {% include "header.html" %}
    </header>

    <div class="content">
      <form method="POST" id="post_form" action="{% url 'blog_app:post_list' %}">
        {% csrf_token %}
        {{ form|safe }}
        {% comment %} <textarea id='content'></textarea> {% endcomment %}
      </form>

      <div class="right_sidebar">
        
        <div class="ai_writer" id="aiAutocompleteButton">
          <img id="ai-img" src="{% static "img/board_write/ai.svg" %}">
          <div id="loading-animation" style="display: none;">
            <img src="{% static 'img/board_write/loading.gif' %}" alt="로딩 중" /></div>
          <div>AI글 자동완성</div>
        </div>

        <div class="topic">
          <div class="topic-name">TOPIC</div>
          <div>
            <form id="topic_form">
              <div>
                <input type="radio" checked name="post_category" value='1'/>
                <label>일상</label>
              </div>
              <div>
                <input type="radio" name="post_category" value='2'/>
                <label>요리</label>
              </div>
              <div>
                <input type="radio" name="post_category" value='3'/>
                <label>여행</label>
              </div>
              <div>
                <input type="radio" name="post_category" value='4'/>
                <label>영화</label>
              </div>
              <div>
                <input type="radio" name="post_category" value='5'/>
                <label>IT</label>
              </div>
            </form>
          </div>
        </div>

        <div class="upload_info">
          <div class="upload_info_name">UPLOAD INFO</div>
          <div>
            {% if status %}
              상태: 게시
            {% else %}
              상태: 미게시
            {% endif %}
          </div>
          
          
          <div class="save_temp_and_submit">
            <button id="save_temp_btn" value="temp" onclick="writePost('temp')">임시저장</button>
            <button id="post_form_btn" value="save" onclick="writePost('save')">글 작성</button>
          </div>
        </div>
      </div>
    </div>

    <footer> {% include 'footer.html' %} </footer>
  </body>

  <script src="{% static 'js/board_write.js' %}"></script>  
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'js/header.js' %}"></script>
  <script src="{% static 'js/ai_write.js' %}"></script>
</html>

blog_project/blog_app/templates/footer.html
<div class="container">
    <p>Made with <span>ONENABLE</span></p>
</div>

blog_project/blog_app/templates/header.html
{% load static %}

<nav>
    <div class="nav_logo" onclick=moveToMain()>
        <img class="nav_logo_img">
    </div>
    <div class="nav_side">
        <input type="text", id="search_box" placeholder="제목이나 내용으로 포스팅을 검색하세요">
        <span class='filter_btn' title="일상" onclick=filtering(1)>일상</span>
        <span class='filter_btn' title="요리" onclick=filtering(2)>요리</span>
        <span class='filter_btn' title="여행" onclick=filtering(3)>여행</span>
        <span class='filter_btn' title="영화" onclick=filtering(4)>영화</span>
        <span class='filter_btn' title="IT" onclick=filtering(5)>IT</span>
        
        {% if user.is_authenticated %}
        <a id="logout" href="{% url 'blog_app:logout' %}">Logout</a>
        <a id="login" href="{% url 'blog_app:write' %}">Justwrite</a>
        {% else %}
        <a id="login" href="{% url 'blog_app:login' %}">Login</a>
        {% endif %}
    </div>
</nav>

blog_project/blog_app/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css'%}?{% now "U" %}"/>
    <title>login</title>
  </head>
  <body>
    <section>
      <h3>Login</h3>
      <form class="box" method="post">
        <div class="idpassword">{% csrf_token %} {{form.as_p}}</div>
        <button class="login" type="submit">login</button>
      </form>
    </section>
  </body>
</html>

blog_project/blog_app/templates/search_results.html
{% extends "./base.html" %} {% block content %}
<form method="GET" action="{% url 'search_view' %}">
  <input type="text" name="q" placeholder="제목 혹은 저자 키워드" />
  <button type="submit">Search</button>
</form>

<ul>
  {% for result in results %}
  <li>{{ result.object }}</li>
  {% endfor %}
</ul>
{% endblock %}